DROP TABLE IF EXISTS recipes CASCADE;

CREATE TABLE recipes (
  id SERIAL PRIMARY KEY NOT NULL,
  api_recipe_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  img_url VARCHAR(255) NOT NULL,
  slot INTEGER NOT NULL
);
